### PR TITLE
Can no longer create records with symbol keys

### LINKED ISSUE #77: Records may only have String keys
**Describe the bug**
According to [proposal-record-tuple](https://github.com/tc39/proposal-record-tuple#runtime-errors), the key of Record can only be a string.

> Records may only have String keys, not Symbol keys, due to the issues described in https://github.com/tc39/proposal-record-tuple/issues/15. Creating a Record with a Symbol key is a TypeError.

**To Reproduce**
```js
const record = #{ [Symbol()]: #{} };
```

**Expected behavior**
It should show the error `// TypeError: Record may only have string as keys`

### PR DESCRIPTION
**Pull request by acutmore**
**Describe your changes**
- Prevents being able to create records with symbol keys. Fixes #77
- Increases spec compliance of `Record.fromEntries` by validating the iterator entry by entry

**Testing performed**
Adds unit tests

### CODE REVIEW

File: packages/record-tuple-polyfill/src/record.js [hunk 1]
```diff
@@ -46,14 +47,17 @@ function createRecordFromObject(value) {
     // sort all property names by the order specified by
     // the argument's OwnPropertyKeys internal slot
     // EnumerableOwnPropertyNames - 7.3.22
-    const properties = Object.entries(value)
+    const properties = Reflect.ownKeys(value)
+        .flatMap(k => {
+            const desc = Object.getOwnPropertyDescriptor(value, k);
+            if (!desc.enumerable) return [];
+            return [[validateKey(k), validateProperty(value[k])]];
```
Comment (acutmore) [inline packages/record-tuple-polyfill/src/record.js:54]: fix here: validate and `toString` the key once
